--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Mohagames205/RGBArmor
build-by-default: true
branches:
- master
projects:
  RGBArmor:
    icon: RGBArmor.png
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.
...
